t1=input('Digite algo: ')
print('t1 é alfanumerico? {}'.format(t1.isalnum()))
print('t1 é apenas letra? {}'.format(t1.isalpha()))
print('t1 é ASCII? {}'.format(t1.isascii()))
print('t1 é decimal? {}'.format(t1.isdecimal()))
print('t1 é digito? {}'.format(t1.isdigit()))
print('t1 é um identificador valido, declarador de variavel? {}'.format(t1.isidentifier()))
#from keyword import iskeyword
#print('t1 é uma palavra reservada?  {}'.format(t1.iskeyword()))
print('t1 é letra minuscula? {}'.format(t1.islower()))
print('t1 é numerico? {}'.format(t1.isnumeric()))
print('t1 é printavel e nao vazio? {}'.format(t1.isprintable()))
print('t1 é espaço? {}'.format(t1.isspace()))
print('t1 é um titulo? {}'.format(t1.istitle()))
print('t1 é letra maiuscula? {}'.format(t1.isupper()))